"""initial schema

Revision ID: 65a0f2c7e0da
Revises: 
Create Date: 2026-09-10 00:41:42.514368
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '65a0f2c7e0da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=16), nullable=False),
    sa.Column('pipeline_version', sa.String(length=16), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scriptures',
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('religion', sa.String(length=16), nullable=False),
    sa.Column('book_or_surah', sa.String(length=128), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_source', sa.String(length=128), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.CheckConstraint("religion in ('bible', 'quran')", name='ck_scripture_religion'),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index('ix_scriptures_location', 'scriptures', ['religion', 'book_or_surah', 'chapter', 'verse'], unique=False)
    op.create_index(op.f('ix_scriptures_religion'), 'scriptures', ['religion'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_religion', sa.String(length=16), nullable=True),
    sa.CheckConstraint("preferred_religion is null or preferred_religion in ('bible', 'quran')", name='ck_user_preferred_religion'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('religion', sa.String(length=16), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_provider', sa.String(length=32), nullable=True),
    sa.Column('analysis_model', sa.String(length=64), nullable=True),
    sa.CheckConstraint("religion in ('bible', 'quran')", name='ck_reflection_religion'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_user_id'), 'reflections', ['user_id'], unique=False)
    op.create_table('scripture_enrichment',
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=16), nullable=False),
    sa.Column('curation_status', sa.String(length=48), nullable=False),
    sa.Column('curation_confidence', sa.Float(), nullable=True),
    sa.Column('rule_fired', sa.String(length=64), nullable=True),
    sa.Column('expressed_primary', sa.String(length=32), nullable=True),
    sa.Column('text_intensity', sa.Integer(), nullable=True),
    sa.Column('standalone_usefulness', sa.Integer(), nullable=True),
    sa.Column('context_dependency', sa.Integer(), nullable=True),
    sa.Column('isolation_risk', sa.Integer(), nullable=True),
    sa.Column('crisis_safe', sa.Boolean(), nullable=True),
    sa.Column('context_span_start', sa.String(length=128), nullable=True),
    sa.Column('context_span_end', sa.String(length=128), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.CheckConstraint("curation_status <> 'INCLUDE_WITH_CONTEXT' or (context_span_start is not null and context_span_end is not null)", name='ck_enrichment_context_span_present'),
    sa.ForeignKeyConstraint(['canonical_id'], ['scriptures.canonical_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_scripture_enrichment_curation_status'), 'scripture_enrichment', ['curation_status'], unique=False)
    op.create_table('reflection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reflection_id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('served_with_context', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['scriptures.canonical_id'], ),
    sa.ForeignKeyConstraint(['reflection_id'], ['reflections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_results_canonical_id'), 'reflection_results', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_reflection_results_reflection_id'), 'reflection_results', ['reflection_id'], unique=False)
    op.create_table('scripture_addressed_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('emotional_relevance', sa.Integer(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['scripture_enrichment.canonical_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'state', name='uq_addressed_state')
    )
    op.create_index(op.f('ix_scripture_addressed_states_canonical_id'), 'scripture_addressed_states', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_scripture_addressed_states_state'), 'scripture_addressed_states', ['state'], unique=False)
    op.create_table('scripture_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=48), nullable=False),
    sa.CheckConstraint("kind in ('advisory', 'avoid_state')", name='ck_advisory_kind'),
    sa.ForeignKeyConstraint(['canonical_id'], ['scripture_enrichment.canonical_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'kind', 'value', name='uq_advisory')
    )
    op.create_index(op.f('ix_scripture_advisories_canonical_id'), 'scripture_advisories', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_scripture_advisories_value'), 'scripture_advisories', ['value'], unique=False)
    op.create_table('scripture_intent_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['scripture_enrichment.canonical_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'intent', name='uq_intent_score')
    )
    op.create_index(op.f('ix_scripture_intent_scores_canonical_id'), 'scripture_intent_scores', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_scripture_intent_scores_intent'), 'scripture_intent_scores', ['intent'], unique=False)
    op.create_table('scripture_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(length=128), nullable=False),
    sa.Column('theme', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['scripture_enrichment.canonical_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id', 'theme', name='uq_scripture_theme')
    )
    op.create_index(op.f('ix_scripture_themes_canonical_id'), 'scripture_themes', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_scripture_themes_theme'), 'scripture_themes', ['theme'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reported_harmful', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['reflection_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_result_id'), 'feedback', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_result_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_scripture_themes_theme'), table_name='scripture_themes')
    op.drop_index(op.f('ix_scripture_themes_canonical_id'), table_name='scripture_themes')
    op.drop_table('scripture_themes')
    op.drop_index(op.f('ix_scripture_intent_scores_intent'), table_name='scripture_intent_scores')
    op.drop_index(op.f('ix_scripture_intent_scores_canonical_id'), table_name='scripture_intent_scores')
    op.drop_table('scripture_intent_scores')
    op.drop_index(op.f('ix_scripture_advisories_value'), table_name='scripture_advisories')
    op.drop_index(op.f('ix_scripture_advisories_canonical_id'), table_name='scripture_advisories')
    op.drop_table('scripture_advisories')
    op.drop_index(op.f('ix_scripture_addressed_states_state'), table_name='scripture_addressed_states')
    op.drop_index(op.f('ix_scripture_addressed_states_canonical_id'), table_name='scripture_addressed_states')
    op.drop_table('scripture_addressed_states')
    op.drop_index(op.f('ix_reflection_results_reflection_id'), table_name='reflection_results')
    op.drop_index(op.f('ix_reflection_results_canonical_id'), table_name='reflection_results')
    op.drop_table('reflection_results')
    op.drop_index(op.f('ix_scripture_enrichment_curation_status'), table_name='scripture_enrichment')
    op.drop_table('scripture_enrichment')
    op.drop_index(op.f('ix_reflections_user_id'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scriptures_religion'), table_name='scriptures')
    op.drop_index('ix_scriptures_location', table_name='scriptures')
    op.drop_table('scriptures')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
