"""reflection status and celery-ready fields

Revision ID: eb04e4534967
Revises: 398ee8e33c41
Create Date: 2026-09-10 13:11:41.213796
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# Autogenerate renders Vector columns as pgvector.sqlalchemy.vector.VECTOR but
# does not emit this import, so every revision would fail with NameError.
import pgvector.sqlalchemy  # noqa: F401


revision = 'eb04e4534967'
down_revision = '398ee8e33c41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills every existing row as 'completed' (accurate:
    # every reflection that predates this migration was persisted only after
    # the old synchronous endpoint had already computed and saved its
    # results), then is dropped so new inserts fall through to the model's
    # Python-side default of 'pending' instead of a DB-level one.
    op.add_column(
        'reflections',
        sa.Column(
            'status', sa.String(length=16), nullable=False, server_default=sa.text("'completed'")
        ),
    )
    op.alter_column('reflections', 'status', server_default=None)
    op.add_column('reflections', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('reflections', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # Autogenerate does not diff CHECK constraints; both are added by hand.
    op.create_check_constraint(
        'ck_reflection_status',
        'reflections',
        "status in ('pending', 'processing', 'completed', 'failed')",
    )
    op.create_check_constraint(
        'ck_reflection_text_present_when_completed',
        'reflections',
        "status <> 'completed' or text is not null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_reflection_text_present_when_completed', 'reflections', type_='check')
    op.drop_constraint('ck_reflection_status', 'reflections', type_='check')
    op.alter_column('reflections', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('reflections', 'error')
    op.drop_column('reflections', 'status')
    # ### end Alembic commands ###
