"""magic link tokens

Revision ID: fac4209f92c2
Revises: eb04e4534967
Create Date: 2026-10-02 08:07:48.046151
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# Autogenerate renders Vector columns as pgvector.sqlalchemy.vector.VECTOR but
# does not emit this import, so every revision would fail with NameError.
import pgvector.sqlalchemy  # noqa: F401


revision = 'fac4209f92c2'
down_revision = 'eb04e4534967'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    # ### end Alembic commands ###
